name: ci-zappy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2.2.0
    - name: make
      run: make re
  test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v2.2.0
    - name: test
      run: |
        cd tests
        npm i
        npm test

